-- Create payrolls table
create table if not exists public.payrolls (
  id bigint generated by default as identity primary key,
  staff_id bigint references public.staffs(id),
  staff_type text not null check (staff_type in ('doctor', 'therapist', 'sales')),
  month text not null,
  start_date date not null,
  end_date date not null,
  base_salary numeric,
  commission numeric,
  total_amount numeric not null,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add indexes
create index if not exists payrolls_staff_id_idx on public.payrolls(staff_id);
create index if not exists payrolls_month_idx on public.payrolls(month);
create index if not exists payrolls_start_date_idx on public.payrolls(start_date);
create index if not exists payrolls_end_date_idx on public.payrolls(end_date);

-- Enable RLS
alter table public.payrolls enable row level security;

-- Create policies
create policy "Enable read access for all users" on public.payrolls
  for select using (true);

create policy "Enable insert for authenticated users only" on public.payrolls
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.payrolls
  for update using (auth.role() = 'authenticated'); 